### ISSUE TITLE
XCSoar seems to crash on Android 8.0

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#120]
Multiple reports in the forum, that Android 8 breaks current stable on startup.

Currently investigating...

**Comment by kicune** [comment]
Can confirm that, happens on my device too. Let me know if you need some logs or any other help.

**Comment by lordfolken** [comment]
@kicune can you dump the adb logcat here in the ticket?

**Comment by lordfolken** [comment]
i tested an android 8.1 device with both stable and master. No issues. Is there some aggressive powersaving that is causing the problem?

**Comment by felixhaedicke** [comment]
Please check if commit fc80aaf (currently on 6.8.x branch) fixes this.

**Comment by flypluswangzhe** [comment]
I have tanslate all word to Chinese , where I can download newest version , such as ver6.8.11 ,and I can test my tanslate word ,my email address is 216188@qq.com thanks,

**Comment by kicune** [comment]
Sorry for the delay, I was travelling. Here is the logcat output.
[XCSoarLog.txt](https://github.com/XCSoar/XCSoar/files/2114682/XCSoarLog.txt)

SIGSYS arrived at 11:30:55.808. As it was related to "Terrain", I tried to switch off the terrain map; it dumped again, this time within "Topography".

For the record, this problem is caused only by version 7.0 compiled by me. Both 7.0 and 6.8 from the app store works, so it may be caused by something from my compile (I used vagrant env. from vanilla master branch).

**Comment by kicune** [comment]
I backported fc80aaf to master (have some compilation problems with v6.8,x atm) and I can confirm that - as far as I was able to check - it works correctly!

**Comment by lordfolken** [comment]
@kicune can you create a pull request?

**Comment by kicune** [comment]
Here: https://github.com/XCSoar/XCSoar/pull/122
I am not sure about the proper way how to do this though, let me know if I should amend something.

**Comment by MaxKellermann** [comment]
fc80aafbbf35eacd26aa9c089f7cf41680efd9ba
