### ISSUE TITLE
Device: LENOVO Tab m8 - XCSoar Fails to start, crash upon fly/sim 

### ISSUE THREAD

**Issue by mccartes** [XCSoar/XCSoar#1392]
XCSoar versions having and not having the problem
-------------------------------------------------

V7.42 (latest on google play) - note when searching on google play only XCsoar JET comes up.  need to go to the website and get the direct link to find the original version.   Neither version works.   I am attaching the log file. 
[xcsoar v7.42 failes to start.log](https://github.com/XCSoar/XCSoar/files/14837927/xcsoar.v7.42.failes.to.start.log)

Which XCSoar version is the last one you know that did not show the problem? I don't know, it used to work fine on my tablet.

System information
------------------

Lenovo tablet TB-7306F, android 11, display 1024 X 600

Steps to reproduce the behavior
-------------------------------

open the app and select either fly or SIM.  App starts to load, and then closes. 

Expected behavior
-----------------

I would expect a map to load. 

Actual behavior
---------------

app closes

Do you have any idea what may have caused this?
-----------------------------------------------

This might give us ideas we haven't thought of, feel free to suggest causes.   No

Do you have an idea how to solve the issue?  No.. already tried a clean install and did a factory reset on the tablet. 

-------------------------------------------

**Comment by ubx** [comment]
Please submit a comprehensive bug report using the provided template, including all relevant questions and details.

**Comment by mccartes** [comment]
I did, but I did not understand the markup language.  It should be readable now.

**Comment by lordfolken** [comment]
#1235 duplicate?

**Comment by mccartes** [comment]
No, that one is in pan mode.  I never get the map screen in the first place.

**Comment by lordfolken** [comment]
Attach a logcat please.

**Comment by mccartes** [comment]
what is a logcat ?

**Comment by lordfolken** [comment]
Logcat, is a log output from android.

The conclusion from the other bug report is, that there is something wrong with the graphics driver stack in that device.
Without access to hardware, this will be hard to debug. Unfortunately this device is in none of the device testing sites (lambdatest, testgrid.io...) i tried. 

Until such time, i can only dis recommend that tablet for XCSoar.

**Comment by mccartes** [comment]
where on the device do I find the Logcat ?

**Comment by lordfolken** [comment]
https://www.xda-developers.com/how-to-take-logs-android/

**Comment by ggajoch** [comment]
Hey, on my device symptoms are the same. Below is my bug report:

If I can help with testing on the device just let me know.

XCSoar versions having the problem
-------------------------------------------------

7.42

XCSoar versions not having the problem
-------------------------------------------------

7.41

System information
------------------

Device: Aquila GPS from PureGliding 
[Website](https://puregliding.fr/)
[Manual](https://puregliding.fr/wp-content/uploads/Ressources/Aquila%20Quick%20Guide.pdf)

Android info:
Model number: m515
Android version: 6.0
Kernel version: 3.18.22
Build number: MRA58K test-keysV1.920210108

I've cleaned XCSoarData folder.

Steps to reproduce the behavior
-------------------------------

Start app, then click fly or sim. 

Expected behavior
-----------------

App launches normally.


Actual behavior
---------------

- app start to load
- loading bar gets to "Initialising display" 
- crashes with "Unfortunately, XCSoar has stopped"

I'm attaching logcat from the crash:
[xcsoar_7.42_crash.log](https://github.com/XCSoar/XCSoar/files/15144701/xcsoar_7.42_crash.log)

**Comment by lordfolken** [comment]
What makes you think that this is the same problem?

**Comment by lordfolken** [comment]
The xcsoar.log is emtpy.

**Comment by ggajoch** [comment]
@lordfolken the version and symptoms are the same.
I've tried again with the XCSoar logs - and I can't see it being created. I've updated my comment above.

Should I open new issue for my device?
