### ISSUE TITLE
Restricted and Danger airspace type show up twice in color settings

### ISSUE THREAD

**Issue by kobedegeest** [XCSoar/XCSoar#1484]
XCSoar versions having the problem
-------------------------------------------------
As of #1349 

XCSoar versions not having the problem
-------------------------------------------------

System information
------------------

Steps to reproduce the behavior
-------------------------------

Look at the airspace color settings.

Expected behavior
-----------------

Every type to be there only once.

Actual behavior
---------------

Restricted and Danger show up twice.

Do you have any idea what may have caused this?
-----------------------------------------------

There are two different possible entries assumed for both these types so two types of restriced and danger are possible. R and res and Q and Danger i believe.

Do you have an idea how to solve the issue?
-------------------------------------------

Merge them as one check for Q or Danger and set to type danger instead of having two entries for this.

**Comment by lordfolken** [comment]
@kobedegeest does my PR fix this aspect for you?

**Comment by lordfolken** [comment]
> @lordfolken do you have a source documentation of the use of DANGER and RESTRICTED in the open or etended open airspace format?

In every header of the OpenAIP-Extended files its described as:
```

* This is OpenAIR file is an extended format derived from the original specification. It adds additional fields:

*  - AY: The AY field contains the type and the AC field is now exclusively used to specify the ICAO class of the defined airspace.
*  - AF: The AF field contains contact frequencies defined for the airspace. If no frequency is defined, this field does not exist.
*  - AG: The AG field contains the ground station call-sign related to the frequency defined for the airspace. If no frequency is defined, this field does not exist.

* This OpenAIR file does contain non-standard AY values. The following list shows all AY types that may be used within this file:
* UNCLASSIFIED, RESTRICTED, DANGER, PROHIBITED, CTR, TMZ, RMZ, TMA, TRA, TSA, FIR, UIR, ADIZ, ATZ, MATZ, AWY, MTR, ALERT, WARNING, PROTECTED, HTZ, GLIDING_SECTOR, TRP, TIZ, TIA, MTA, CTA, ACC_SECTOR, AERIAL_SPORTING_RECREATIONAL, OVERFLIGHT_RESTRICTION, MRT, TFR, VFR_SECTOR, FIS_SECTOR, LTA, UTA

* This OpenAIR file does contain non-standard AC values. The following list shows all AC types that may be used within this file:
* A, B, C, D, E, F, G, UNCLASSIFIED
```

> All i find is Q for danger and R for restricted. 

http://winpilot.com/usersguide/userairspace.asp
According to this it should be Q / R in the AY Field. 

@reskume what was your reasoning for writing RESTRICTED and DANGER into the AY fields, instead of Q/R ? Which way should we go forward?

> I also see no reason to have two options point to the same airspace type.

XCSoar parses AC and AY fields, so already there we point with multiple entries to the same internal Airspace type. 

My latest commits address the dublication now. (and other issues...)

**Comment by lordfolken** [comment]
> FYI same then for PROHIBITED used to be P now the extended format uses PROHIBITED but code still only checks for P. I think just based of reading code have not tested yet.

https://github.com/XCSoar/XCSoar/pull/1506/commits/d9295ac311817ebcc99c99e6b2bb34349583e1fc

**Comment by reskume** [comment]
@lordfolken The reason behind this was very simple: the values used should be plain and simple to understand. And since they change a lot, i.e. new "type" (AC) values are added very often, there is also the header information so that each file is self explaining and also reflects the values used at the point of export.

There is a repo here where Naviter defines "their" accepted values for OpenAIR files: https://github.com/naviter/seeyou_file_formats/blob/main/OpenAir_File_Format_Support.md

Maybe we all should group together and try to find a common middle ground that works for all with a defined set of accepted values. In that case, openAIP will map all internal types that are not in the definition to the most appropriate, e.g. "overflightrestriction -> P" and so.

What do you think?

**Comment by lordfolken** [comment]
> @lordfolken The reason behind this was very simple: the values used should be plain and simple to understand. And since they change a lot, i.e. new "type" (AC) values are added very often, there is also the header information so that each file is self explaining and also reflects the values used at the point of export.

I see your point. :)

> There is a repo here where Naviter defines "their" accepted values for OpenAIR files: https://github.com/naviter/seeyou_file_formats/blob/main/OpenAir_File_Format_Support.md

Oh this is news to me. 
> Maybe we all should group together and try to find a common middle ground that works for all with a defined set of accepted values. In that case, openAIP will map all internal types that are not in the definition to the most appropriate, e.g. "overflightrestriction -> P" and so.

> What do you think?
Full on. I found your discussion https://github.com/naviter/seeyou_file_formats/discussions/4
