### ISSUE TITLE
Building XCSoar with CMake

### ISSUE THREAD

**Issue by Tymolc** [XCSoar/XCSoar#155]
Hi!

I recently decided that I might want to look further into contributing to XCSoar.
I feel like the build system is kind of difficult to grasp, especially for non-Linux devs, so I was thinking about providing a CMake alternative for building with conan as a dependency manager.
My desired outcome would be that it is possible to build XCSoar natively on all desktop operating systems (disclaimer: I unfortunately have very little experience with Android and iOS development).

Did anyone look into this before and would this be a desired change?

Feedback is very welcome.

**Comment by MaxKellermann** [comment]
9 years ago, [I suggested moving to autotools](http://xcsoar.1045713.n5.nabble.com/A-few-general-questions-on-development-td2650276.html), but it was vetoed.

As much as I've tried to optimize our Makefile over the last 9 years, it's still horrible. So yes, I'd look forward to switch to something else. Meanwhile, I've moved past autotools, now this had to wait until [Meson](https://mesonbuild.com/) emerged (I've [switched MPD to Meson](https://github.com/MusicPlayerDaemon/MPD/commit/94592c14062d5afc9482d11baa401648082022c0) which is as complex was XCSoar). I've always hated CMake, and never considered it superior to autotools, which is why I was stuck with autotools for so long.

In any case:
- a submission which omits any currently supported target cannot be merged, so any volunteer needs to figure out all targets (iOS is not a supported target, but Android certainly is)
- there will not be two build systems; the submission must delete the old build scripts

As much as I hate CMake, and as much as I'd prefer you to use Meson instead, the guy who does the job (and is willing to keep supporting it) may decide. I will not veto a well-done and complete CMake port.

**Comment by Tymolc** [comment]
Thanks for your quick reply.
I agree that CMake can be very painful. I guess it might be Stockholm syndrome, but I've gotten kind of used to it. I am happy to look into Meson though. New projects are always a way to learn new things, after all!

**Comment by Exadios** [comment]
I have a branch on Exadios/XCSoar and Exadios/xcsoar-exp called 'master-cmake-build' which may be of interest to you. Presently it only builds the "UNIX" target for the master branch. I use it for debugging since it generally does a faster and better job of building code changes than the supplied Makefile (I use ninja as the back end build agent). This branch is currently up to date with the current master branch.

**Comment by sbrodehl** [comment]
What is the current state here?

**Comment by Tymolc** [comment]
I would still very much like to do this, but unfortunately I don’t see that I will have the time in the closer future ... sorry
