### ISSUE TITLE
Describe Waypoint_Details file format in XCSoar User Manual

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#242]
The documentation does not describe the waypoint_details file anywhere. 

The Format is currently: 
[WAYPOINT_NAME] <- must match way point in cup
Text Text
Multiline <= appears in the description field and as long text on the following way-point page
file=/relative/url/to/xcsoardata=*.jpg <= clickable file to open with default associated picture viewer
file=/relative/url/to/xcsoardata=*.pdf <= clickable file to open with default associated image viewer
image=/relative/url/to/xcsoardata/*.png image displayed with zoom etc.

**Comment by Buzz33** [comment]
Try to update the manual relating to the the waypoint details - during the next weeks.

**Comment by Buzz33** [comment]
By using Github desktop I finally updated the tex files of Ch4 Tasks, CH Installation, Ch11 Configuration and CH12 data files - in German language. I also described "displaying pictures" in XCSoar, using an example with some additional screenshots whitch I uploaded to "figures" . It is in my forked repository by now, pushed to master. 

What is to do next? Maybe some advise would be useful, before I mess up anything  - because I am perfectly new to github and tex. ;-)
