### ISSUE TITLE
Negative ground speed vector

### ISSUE THREAD

**Issue by chickenzown** [XCSoar/XCSoar#249]
So XCSoar displays ground speed via GPS, is it possible for it to display a negative ground speed based upon steering vector if travelling backwards?  An issue occured recently during paragliding when the display indicated a ground speed of 5kts whilst relative to the ground the paraglider was travelling dangerously backwards.

**Comment by kerel-fs** [comment]
The ground speed is always positive, since it is calculated by measuring the distance between the `last_location` and the current location (`basic.location`) divided by the elapsed time between those fixes, see
https://github.com/XCSoar/XCSoar/blob/719cedbf614b037c75081fa86f7be3735fb0daf4/src/Computer/GroundSpeedComputer.cpp#L40-L49

If no compass is connected, the heading is calculated as the following:
https://github.com/XCSoar/XCSoar/blob/74e8d4e040a9f92ab6849a5e5ceb8f31bcaa710e/src/Computer/BasicComputer.cpp#L132-L166
