### ISSUE TITLE
Altitude not used when replaying an IGC file

### ISSUE THREAD

**Issue by Flying-Roger** [XCSoar/XCSoar#604]
XCSoar versions having and not having the problem
-------------------------------------------------
Android XCSoar version 7.6 has the problem.
The problem was also there in previous Android versions.
Fortunately, there is no such problem in the Windows version.

Expected behavior
-----------------
When replaying an IGC file, I would expect that all elements related to the altitude are calculated based on the recorded altitude.

Current behavior
-------------------
Only the "GPS Altitude" is working, while the other altitude and variometer elements are frozen.
Due to this, it is not possible to really get experienced with all XCSoar functions by replaying IGC files.

Steps to reproduce the behavior
-------------------------------
Config 2 > Replay > load an IGC file > Start

Do you have any idea what may have caused this?
--------------------------------------------------------
No

Do you have an idea how to solve the issue?
-------------------------------------------------
Probably the bug can be fixed by copying the GPS altitude from the IGC file onto the "Baro Altitude".

**Comment by MaxKellermann** [comment]
Can't reproduce. If I replay IGC files, I get valid altitudes and vario values.
Your bug report does not contain any sample IGC file.

**Comment by FlyingRoger** [comment]
Sorry for not providing a sample IGC.
Actually, I had the problem with any IGC, all recorded without barometric data.
Today, I tested today with version 7.15-Android dated Aug 19, 2021.
Good news = the problem is seemingly solved with this version: vario/altitude related data are now operating during a replay of my IGC files.

Many thanks to the developper who fixed the problem !

**Comment by FlyingRoger** [comment]
Sorry for coming back on this issue, but the problem is actually not solved.
However, I found an interesting element:
- The problem temporarily disappears if, during the replay, I click on the "+10'" button.
Then the vario becomes effective and the AGL altitude becomes correct as long as the replay moves ahead in accelerated mode.
When it resumes at the specified speed (1x, 2x,...), the vario fails again and the AGL altitude is again wrong (negative).
[Sample_IGC_vario_problem.txt](https://github.com/XCSoar/XCSoar/files/7076479/Sample_IGC_vario_problem.txt)
![XCSOAR 1 - replay wrong AGL - no vario](https://user-images.githubusercontent.com/61454111/131335731-68309b10-425d-4506-9cf8-9164b9916ced.png)
![XCSOAR 2 - fast replay (+10 minutes) - AGL OK - vario OK](https://user-images.githubusercontent.com/61454111/131335734-5ee600ad-c09b-4d79-a870-f2c3148aa54b.png)
![XCSOAR 3 - replay normal speed - wrong AGL - no vario](https://user-images.githubusercontent.com/61454111/131335736-eebcc2fa-99f6-4408-8d4b-c9b42b4ca9a9.png)
Here attached a few snapshots to show this.
I also provide a short igc to reproduce the problem.
