### ISSUE TITLE
ARM Start post crossing start line, should advance to first waypoint

### ISSUE THREAD

**Issue by lordfolken** [XCSoar/XCSoar#947]
XCSoar version
--------------
7.23

What should XCSoar do differently, what functionality should be added?
----------------------------------------------------------------------
The Arm Start option should help to prevent crossing the starting line accidently and starting the task. 
When Arm Start is configured and the start line/sector is crossed, a popup appears at the bottom of the page:

![2022-06-14-174343_681x741_scrot](https://user-images.githubusercontent.com/407371/173619845-bae80422-c15e-404b-af48-e280d052994f.png)

When Pressing arm, the task still points back to the start line:

![2022-06-14-174502_681x741_scrot](https://user-images.githubusercontent.com/407371/173620054-3cfd3afc-be81-4dd7-bded-0d2ac91b56f0.png)

It should instead point to the first waypoint. 
What are you trying to do, what is the use case for the suggestion?
-------------------------------------------------------------------

XCSoar should be as hands-free during flight as possible. If you press arm start after crossing the finish line, you have already started on the task. The Task should therefore point to the first waypoint.

**Comment by MaxKellermann** [comment]
>  When Arm Start is configured and the start line/sector is crossed, a popup appears at the bottom of the page:

No, the popup appears when you enter the OZ, not when you cross the line.

If you arm *after* crossing the line, it's too late already, and XCSoar's behavior is correct. Because it means you have crossed the line without arming the start point, therefore crossing the line doesn't count. You need to cross the line *after* arming the start point.

> If you press arm start after crossing the finish line, you have already started on the task. The Task should therefore point to the first waypoint.

No. The whole point of this option is exactly *not* that, it's the opposite: make crossing the line *not* count until you arm the start point.
